// <auto-generated />
namespace CalculatorApp.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CalculatorApp1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CalculatorApp1));
        
        string IMigrationMetadata.Id
        {
            get { return "202205200859353_CalculatorApp1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
